# Generated by Django 4.0.10 on 2023-02-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('review', models.TextField()),
                ('publish', models.BooleanField(default=True)),
            ],
        ),
    ]
